
from PyQt6 import QtCore, QtGui, QtWidgets
import logic


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 503)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 391, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Title = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.Title.setObjectName("Title")
        self.verticalLayout.addWidget(self.Title)
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 80, 371, 33))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.idLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.idLabel.setFont(font)
        self.idLabel.setObjectName("idLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.idLabel)
        self.idEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.idEdit.setObjectName("idEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.idEdit)
        self.canidateLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.canidateLabel.setGeometry(QtCore.QRect(110, 150, 191, 31))
        self.canidateLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.canidateLabel.setObjectName("canidateLabel")
        self.formLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(49, 299, 321, 33))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setVerticalSpacing(20)
        self.formLayout_3.setObjectName("formLayout_3")
        self.writeinLabel = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.writeinLabel.setObjectName("writeinLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.writeinLabel)
        self.writeinEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.writeinEdit.setObjectName("writeinEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.writeinEdit)
        self.johnRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.johnRadio.setGeometry(QtCore.QRect(170, 250, 71, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.johnRadio.sizePolicy().hasHeightForWidth())
        self.johnRadio.setSizePolicy(sizePolicy)
        self.johnRadio.setObjectName("johnRadio")
        self.janeRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.janeRadio.setGeometry(QtCore.QRect(170, 200, 71, 29))
        self.janeRadio.setAutoExclusive(True)
        self.janeRadio.setObjectName("janeRadio")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(79, 349, 261, 35))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(100)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.totalButt = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.totalButt.setObjectName("totalButt")
        self.horizontalLayout.addWidget(self.totalButt)
        self.voteButt = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.voteButt.setObjectName("voteButt")
        self.horizontalLayout.addWidget(self.voteButt)
        self.outputLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(6, 412, 421, 61))
        self.outputLabel.setText("")
        self.outputLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.outputLabel.setFont(font)
        self.formLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(29, 389, 371, 127))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.voteTotalLayout = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.voteTotalLayout.setContentsMargins(0, 0, 0, 0)
        self.voteTotalLayout.setObjectName("voteTotalLayout")
        self.voteTotalLabel1a = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.voteTotalLabel1a.setFont(font)
        self.voteTotalLabel1a.setText("")
        self.voteTotalLabel1a.setObjectName("voteTotalLabel1a")
        self.voteTotalLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.voteTotalLabel1a)
        self.voteTotalLabel2a = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.voteTotalLabel2a.setFont(font)
        self.voteTotalLabel2a.setText("")
        self.voteTotalLabel2a.setObjectName("voteTotalLabel2a")
        self.voteTotalLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.voteTotalLabel2a)
        self.voteTotalLabel3a = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.voteTotalLabel3a.setFont(font)
        self.voteTotalLabel3a.setText("")
        self.voteTotalLabel3a.setObjectName("voteTotalLabel3a")
        self.voteTotalLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.voteTotalLabel3a)
        self.voteTotalLabel4a = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.voteTotalLabel4a.setFont(font)
        self.voteTotalLabel4a.setText("")
        self.voteTotalLabel4a.setObjectName("voteTotalLabel4a")
        self.voteTotalLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.voteTotalLabel4a)
        self.voteTotalLabelOtherA = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.voteTotalLabelOtherA.setFont(font)
        self.voteTotalLabelOtherA.setText("")
        self.voteTotalLabelOtherA.setObjectName("voteTotalLabelOtherA")
        self.voteTotalLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.voteTotalLabelOtherA)
        self.voteTotalLabel1b = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.voteTotalLabel1b.setFont(font)
        self.voteTotalLabel1b.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.voteTotalLabel1b.setAutoFillBackground(False)
        self.voteTotalLabel1b.setText("")
        self.voteTotalLabel1b.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.voteTotalLabel1b.setObjectName("voteTotalLabel1b")
        self.voteTotalLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.voteTotalLabel1b)
        self.voteTotalLabel2b = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.voteTotalLabel2b.setFont(font)
        self.voteTotalLabel2b.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.voteTotalLabel2b.setAutoFillBackground(False)
        self.voteTotalLabel2b.setText("")
        self.voteTotalLabel2b.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.voteTotalLabel2b.setObjectName("voteTotalLabel2b")
        self.voteTotalLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.voteTotalLabel2b)
        self.voteTotalLabel3b = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.voteTotalLabel3b.setFont(font)
        self.voteTotalLabel3b.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.voteTotalLabel3b.setAutoFillBackground(False)
        self.voteTotalLabel3b.setText("")
        self.voteTotalLabel3b.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.voteTotalLabel3b.setObjectName("voteTotalLabel3b")
        self.voteTotalLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.voteTotalLabel3b)
        self.voteTotalLabel4b = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.voteTotalLabel4b.setFont(font)
        self.voteTotalLabel4b.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.voteTotalLabel4b.setAutoFillBackground(False)
        self.voteTotalLabel4b.setText("")
        self.voteTotalLabel4b.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.voteTotalLabel4b.setObjectName("voteTotalLabel4b")
        self.voteTotalLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.voteTotalLabel4b)
        self.voteTotalLabelOtherB = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.voteTotalLabelOtherB.setFont(font)
        self.voteTotalLabelOtherB.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.voteTotalLabelOtherB.setAutoFillBackground(False)
        self.voteTotalLabelOtherB.setText("")
        self.voteTotalLabelOtherB.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.voteTotalLabelOtherB.setObjectName("voteTotalLabelOtherB")
        self.voteTotalLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.voteTotalLabelOtherB)
        MainWindow.setCentralWidget(self.centralwidget)
        

        #onpress
        self.voteButt.clicked.connect(lambda: logic.vote(self))
        self.totalButt.clicked.connect(lambda: logic.voteTotal(self))


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def getId(self):
        return self.idEdit.text()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voting Application"))
        self.Title.setText(_translate("MainWindow", "Vote Now"))
        self.idLabel.setText(_translate("MainWindow", "ID"))
        self.canidateLabel.setText(_translate("MainWindow", "Canidates"))
        self.writeinLabel.setText(_translate("MainWindow", "Write-In"))
        self.johnRadio.setText(_translate("MainWindow", "John"))
        self.janeRadio.setText(_translate("MainWindow", "Jane"))
        self.totalButt.setText(_translate("MainWindow", "Total"))
        self.voteButt.setText(_translate("MainWindow", "Vote"))
